have_fun: true  # 코드 검토에 재미있는 요소를 추가할지 여부 (덜 엄격한 검토)

code_review:  # 코드 검토 기능 설정
  disable: false  # 코드 검토 기능 활성화 여부 (false: 활성화)
  comment_severity_threshold: MEDIUM  # 표시할 코멘트의 최소 심각도 (MEDIUM, HIGH 등)
  max_review_comments: -1  # 허용되는 최대 리뷰 코멘트 수 (-1: 제한 없음)

  pull_request_opened:  # 풀 리퀘스트가 열렸을 때 수행할 작업
    help: true  # 도움이 되는 제안 활성화 여부 (false: 비활성화)
    summary: true  # 변경 사항 요약 생성 여부 (true: 생성)
    code_review: true  # 자동 코드 검토 실행 여부 (true: 실행)
